# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

##### -------------------------------------------------
##### Basic environment
##### -------------------------------------------------

# Preferred editor
export EDITOR="nvim"

# History settings
HISTFILE="$HOME/.zsh_history"
HISTSIZE=100000
SAVEHIST=100000

setopt HIST_IGNORE_DUPS       # don't record dupes
setopt HIST_IGNORE_SPACE      # don't record lines starting with space
setopt HIST_FIND_NO_DUPS      # skip dupes when searching history
setopt SHARE_HISTORY          # share history across shells

# Useful shell options
setopt AUTO_CD                # `cd foo` -> just `foo`
setopt AUTO_PUSHD             # pushd on cd
setopt PUSHD_SILENT
setopt PUSHD_IGNORE_DUPS
setopt CORRECT                # spelling correction for commands
setopt EXTENDED_GLOB
setopt NO_BEEP

# Case-insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# Prompt shows current directory only, not full path, in completion menus
zstyle ':completion:*:default' list-colors ''
zstyle ':completion:*' menu select

# Put ~/.local/bin etc in PATH if not already there
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"


##### -------------------------------------------------
##### Completion system
##### -------------------------------------------------

# load completion system
autoload -Uz compinit
compinit -i


##### -------------------------------------------------
##### fzf integration
##### -------------------------------------------------
# We want: Ctrl-R history search, and tab completion powered by fzf.

# On NixOS, global packages are symlinked under /run/current-system/sw.
# We source from there instead of hardcoding the /nix/store hash.
if [ -f /run/current-system/sw/share/fzf/key-bindings.zsh ]; then
  source /run/current-system/sw/share/fzf/key-bindings.zsh
fi

if [ -f /run/current-system/sw/share/fzf/completion.zsh ]; then
  source /run/current-system/sw/share/fzf/completion.zsh
fi

# (Optional but nice) tweak fzf default options
export FZF_DEFAULT_OPTS='--height=40% --reverse --border'


##### -------------------------------------------------
##### zsh plugins: autosuggestions + syntax highlighting
##### (optional, but very nice for everyday use)
##### -------------------------------------------------

# Autosuggestions: ghost text to the right
if [ -f /run/current-system/sw/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
  source /run/current-system/sw/share/zsh-autosuggestions/zsh-autosuggestions.zsh
  # make the suggested text a bit dimmer
  ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#555555'
fi

# Syntax highlighting: colors as you type
# NOTE: must be sourced *after* compinit, and usually last before the prompt
if [ -f /run/current-system/sw/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source /run/current-system/sw/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi


##### -------------------------------------------------
##### Powerlevel10k prompt
##### -------------------------------------------------
# You installed zsh-powerlevel10k in NixOS, so it's available at:
#   /run/current-system/sw/share/zsh-powerlevel10k/powerlevel10k.zsh-theme
#
# First source the theme, then (if it exists) source your personal config
# from ~/.p10k.zsh. That file is generated by running `p10k configure`.

if [ -f /run/current-system/sw/share/zsh-powerlevel10k/powerlevel10k.zsh-theme ]; then
  source /run/current-system/sw/share/zsh-powerlevel10k/powerlevel10k.zsh-theme
fi

# Your custom prompt config (colors, icons, segments, etc.)
if [ -f "$HOME/.p10k.zsh" ]; then
  source "$HOME/.p10k.zsh"
fi


##### -------------------------------------------------
##### Aliases / quality of life
##### -------------------------------------------------

# Safer rm/mv/cp
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

# Shortcuts
alias ll='ls -lah --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'

# Git sugar
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'

# Reload shell config quickly
alias reload-zsh='source ~/.zshrc'

##### -------------------------------------------------
##### End
##### -------------------------------------------------

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
